// Regenerate assets/vendor/pdfjs/pdf.embed.js after updating the vendored
// pdf.js. The embed lets index.html open PDFs when loaded from disk (file://),
// where browsers block ES module and worker files.
import { readFileSync, writeFileSync } from 'node:fs';

const dir = new URL('../assets/vendor/pdfjs/', import.meta.url);
const lib = readFileSync(new URL('pdf.min.mjs', dir), 'utf8');
const worker = readFileSync(new URL('pdf.worker.min.mjs', dir), 'utf8');
const out =
  '// Generated by scripts/embed-pdfjs.mjs from pdf.min.mjs and pdf.worker.min.mjs; do not edit.\n' +
  `globalThis.ColormerisPdfjsSource = ${JSON.stringify({ lib, worker })};\n`;
writeFileSync(new URL('pdf.embed.js', dir), out);
console.log(`wrote pdf.embed.js (${(out.length / 1e6).toFixed(2)} MB)`);
