"""Write assets/js/cmap-data.js with the matplotlib colormaps for colormaps.html.

Run:  uv run --with matplotlib python scripts/export-mpl-colormaps.py

Continuous maps are sampled at 256 evenly spaced points (matplotlib's own
lookup-table size); qualitative maps keep their listed colors. Groups follow the
categories of matplotlib's colormap reference, regrouped into sequential,
diverging, cyclic, rainbow and others.
"""
import json
from pathlib import Path

import matplotlib
from matplotlib import colormaps
from matplotlib.colors import ListedColormap, to_hex

# Aliases (grey, Grays, gist_grey, gist_yerg) and _r variants are left out.
# (group, sub-heading, names); order is the display order.
GROUPS = [
    ("sequential", "Perceptually uniform", ["viridis", "plasma", "inferno", "magma", "cividis"]),
    ("sequential", "Sequential", ["Greys", "Purples", "Blues", "Greens", "Oranges", "Reds",
                                  "YlOrBr", "YlOrRd", "OrRd", "PuRd", "RdPu", "BuPu", "GnBu",
                                  "PuBu", "YlGnBu", "PuBuGn", "BuGn", "YlGn"]),
    ("sequential", "Sequential (2)", ["binary", "gist_yarg", "gist_gray", "gray", "bone", "pink",
                                      "spring", "summer", "autumn", "winter", "cool", "Wistia",
                                      "hot", "afmhot", "gist_heat", "copper"]),
    ("diverging", "", ["PiYG", "PRGn", "BrBG", "PuOr", "RdGy", "RdBu", "RdYlBu", "RdYlGn",
                       "coolwarm", "bwr", "seismic", "berlin", "managua", "vanimo"]),
    ("cyclic", "", ["twilight", "twilight_shifted", "hsv"]),
    ("rainbow", "", ["jet", "rainbow", "gist_rainbow", "turbo", "nipy_spectral", "gist_ncar", "Spectral"]),
    ("others", "Qualitative", ["Pastel1", "Pastel2", "Paired", "Accent", "Dark2", "Set1", "Set2",
                               "Set3", "tab10", "tab20", "tab20b", "tab20c", "okabe_ito"]),
    ("others", "Miscellaneous", ["flag", "prism", "ocean", "gist_earth", "terrain", "gist_stern",
                                 "gnuplot", "gnuplot2", "CMRmap", "cubehelix", "brg"]),
]

N = 256


def colors_of(cmap, qualitative):
    if qualitative:
        rgba = cmap.colors
    else:
        rgba = cmap([i / (N - 1) for i in range(N)])
    return "".join(to_hex(c)[1:] for c in rgba)


maps = []
for group, sub, names in GROUPS:
    for name in names:
        cmap = colormaps[name]
        qualitative = sub == "Qualitative"
        assert not qualitative or isinstance(cmap, ListedColormap), name
        maps.append({
            "name": name,
            "group": group,
            "sub": sub,
            "kind": "qualitative" if qualitative else "continuous",
            "colors": colors_of(cmap, qualitative),
        })

data = {"source": "matplotlib", "version": matplotlib.__version__, "maps": maps}
out = Path(__file__).resolve().parent.parent / "assets" / "js" / "cmap-data.js"
out.write_text(
    "// Generated by scripts/export-mpl-colormaps.py; do not edit by hand.\n"
    "// Colors are 6-digit hex strings concatenated (256 samples, or the listed colors).\n"
    "(function (CM) {\n"
    "  'use strict';\n"
    f"  CM.cmapData = {json.dumps(data, separators=(',', ':'))};\n"
    "})((globalThis.Colormeris ??= {}));\n"
)
print(f"wrote {out} ({len(maps)} maps, matplotlib {matplotlib.__version__})")
